check dvc.lock changes

diff --git a/.github/workflows/integration.yml b/.github/workflows/integration.yml
--- a/.github/workflows/integration.yml
+++ b/.github/workflows/integration.yml
@@ -51,8 +51,8 @@ jobs:
           dvc repro
           echo "DVC pipeline completed."
 
-      - name: Check DVC status
+      - name: Check for uncommitted changes in dvc.lock or .dvc files
         run: |
-          echo "Checking if dvc.lock is up to date..."
-          git diff --exit-code dvc.lock || (echo "dvc.lock is not up to date. Please run 'dvc repro'." && exit 1)
-          echo "DVC status check completed."
+          git status
+          git diff --exit-code dvc.lock || (echo "::error::dvc.lock is outdated. Please run 'dvc repro' and commit changes." && exit 1)
+          git diff --exit-code '*.dvc' || (echo "::error::Some .dvc files changed but are not committed." && exit 1)
